### ISSUE TITLE
Unused Inputs to Management Area

### ISSUE THREAD

**Issue by yrrapt** [efabless/caravel_mpw-one#17]
It is not known if unused inputs to the management area need to be terminated in the user space. To the best of my knowledge there's no documentation for how to treat these signals.

If they are not terminated then the digital gates will have undefined values and could lead to large increase in power. Will eFabless terminate these pins or is it the user's responsibility?

**Comment by RTimothyEdwards** [comment]
As of the Caravel design for MPW-two and following, the "management protect" block multiplexes all inputs coming from the user area and will ground them as seen by the management SoC by default.  These are the logic analyzer input enable lines (`la_iena_mprj` signals in caravel.v).  Since there are also IRQ lines from the user project back to the processor, these also have input enable lines and are grounded by default if unused.  So from MPW-two, the user project needs only to route connections to the logic analyzer that it uses, and can leave all others open-circuit.
